default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: postgres

development:
  <<: *default
  database: orangeconverter_development

test:
  <<: *default
  database: orangeconverter_test

production:
  <<: *default
  database: orangeconverter_production
